### PR TITLE
Vani branch

### PR DESCRIPTION
**Pull request by vani-chetan**
Lombok dependency added in pom.xml

### CODE REVIEW

**Comment by vani-chetan** [comment]
added new list for search

**Review by vani-chetan — COMMENTED** [review]
reviewed files for conflits

**Comment by vani-chetan** [comment]
merged

**Comment by sgami444** [comment]
Ready to merge in the main branch, do you want me to proceed?

**Comment by vani-chetan** [comment]
Yes please!!!

**Comment by vani-chetan** [comment]
Thanks!!!!

**Pull request merged**
